DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS login_attempts;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS session_data;

DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS keystore;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS financials;
DROP TABLE IF EXISTS ip_blacklist;
